name: Quality Phase

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build & Analysis
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.2"

      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-

      - name: Resolve Swift Package dependencies
        run: |
          xcodebuild \
            -project Modulo.xcodeproj \
            -scheme Modulo \
            -resolvePackageDependencies

      - name: Build
        run: |
          xcodebuild build \
            -project Modulo.xcodeproj \
            -scheme Modulo \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -configuration Debug \
            | xcpretty

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --quiet --reporter json > sonarqube-swiftlint.json

      - name: mobsfscan
        uses: MobSF/mobsfscan@0.3.6
        with:
          args: '. --sarif -o mobsfscan-report.sarif'

      - uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
